### ISSUE TITLE
Use 'glassfish/openjdk', or be inspire by it

### ISSUE THREAD

**Issue by brunoborges** [AdamBien/docklands#2]
Instead of using CentOS base image, consider using glassfish/openjdk (or produce something similar). It is published on Docker Hub and is based on Alpine Linux. It is very minimalistic, very small, and still 100% functional.

**Comment by Urbiwanus** [comment]
Check https://developer.atlassian.com/blog/2015/08/minimal-java-docker-containers/ for further informations 
Regards

**Comment by brunoborges** [comment]
@Urbiwanus the glassfish/openjdk uses those approaches, and also fixes the SSL issues by installing the CA certificates in OpenJDK (which are not provided by default)

**Comment by AdamBien** [comment]
I took a look at alpine linux. Looks interesting - however, it seems like there are no official openjdk8-devel images available. Also: the size of the image should not matter, because it only exists once on the disc. Are there any runtime performance differences? Most of my clients are using CentOs, none of them is alpine based...
